version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://ziedsagguem:LEAVE1234@cluster0.qvb9e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=sdcchjcverr/5456efceecez//
      - NODE_ENV=development
    depends_on:
      - frontend